version: '3'
services:
  discord-bot-ncls:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
      - UPTIME_ROBOT_API_KEY=${{ secrets.UPTIME_ROBOT_API_KEY }}
    restart: unless-stopped
