name: Deploy

on:
    push:
        branches:
            - main

jobs:
    uploadFiles:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Clone repository on VPS
              run: |
                  ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} << 'EOF'
                    if [ ! -d "/home/blury/bot/discord/ncls" ]; then
                      git clone git@github.com:ncls-p/discord-bot-terracraft.git /home/blury/bot/discord/ncls
                    else
                      cd /home/blury/bot/discord/ncls
                      git pull
                    fi
                  EOF

    buildImageBot:
        needs: uploadFiles
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build Docker image
              run: |
                  ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} << 'EOF'
                    cd /home/blury/bot/discord/ncls
                    docker build -f docker/Dockerfile -t discord-bot-ncls .
                  EOF

    startDockerBot:
        needs: buildImageBot
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Start Docker containers
              run: |
                  ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} << 'EOF'
                    cd /home/blury/bot/discord/ncls
                    docker-compose -f docker-compose.yml up -d
                  EOF
