name: Deploy

on:
    push:
        branches:
            - main

jobs:
    uploadFiles:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Clone repository on VPS
              run: |
                  echo "${{ secrets.SSHKEY }}" > deploy_key
                  chmod 600 deploy_key
                  ssh -i deploy_key -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} << 'EOF'
                    if [ ! -d "/home/blury/bot/discord/terracraft" ]; then
                      git clone git@github.com:ncls-p/discord-bot-terracraft.git /home/blury/bot/discord/terracraft
                    else
                      cd /home/blury/bot/discord/terracraft
                      git pull
                    fi
                  EOF

    buildImageBot:
        needs: uploadFiles
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Clone repository on VPS
              run: |
                  echo "${{ secrets.SSHKEY }}" > deploy_key
                  chmod 600 deploy_key
                  ssh -i deploy_key -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} << 'EOF'
                    if [ ! -d "/home/blury/bot/discord/terracraft" ]; then
                      git clone git@github.com:ncls-p/discord-bot-terracraft.git /home/blury/bot/discord/terracraft
                    else
                      cd /home/blury/bot/discord/terracraft
                      git pull origin main
                    fi
                  EOF

    startDockerBot:
        needs: buildImageBot
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Start Docker containers
              run: |
                  echo "${{ secrets.SSHKEY }}" > deploy_key
                  chmod 600 deploy_key
                  ssh -i deploy_key -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} << 'EOF'
                    cd /home/blury/bot/discord/terracraft
                    docker-compose -f docker-compose.yml up -d
                  EOF
