name: Deploy

on: [push]

jobs:
    updateFiles:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Executing remote command
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: ${{ secrets.PORT }}
                  key: ${{ secrets.SSHKEY }}
                  script: |
                      if [ ! -d "/home/blury/bot/discord/discord-bot-terracraft" ]; then
                          git clone git@github.com:ncls-p/discord-bot-terracraft.git /home/blury/bot/discord/discord-bot-terracraft
                      else
                          cd /home/blury/bot/discord/discord-bot-terracraft && git pull
                      fi

    buildImageBot:
        needs: updateFiles
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Executing remote command
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: ${{ secrets.PORT }}
                  key: ${{ secrets.SSHKEY }}
                  script: |
                      cd /home/blury/bot/discord/discord-bot-terracraft &&
                        docker build -f docker/Dockerfile -t discord-bot-terracraft .

    startDockerBot:
        needs: buildImageBot
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Executing remote command
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: ${{ secrets.PORT }}
                  key: ${{ secrets.SSHKEY }}
                  envs: DISCORD_BOT_PREFIX,DISCORD_BOT_TOKEN,OPENAI_API_KEY,DISCORD_BOT_CREATOR
                  script: |
                      cd /home/blury/bot/discord/discord-bot-terracraft &&
                      docker-compose down &&
                      docker-compose up -d
