name: Deploy

on: [push]

jobs:
    updateFiles:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Executing remote command
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: ${{ secrets.PORT }}
                  key: ${{ secrets.SSHKEY }}
                  script: |
                      if [ ! -d "/home/blury/bot/discord/discord-bot-terracraft" ]; then
                        git clone -v git@github.com:ncls-p/discord-bot-terracraft.git /home/blury/bot/discord/discord-bot-terracraft

                      else
                          cd /home/blury/bot/discord/discord-bot-terracraft && git pull
                      fi

    startAndBuildDockerBot:
        needs: updateFiles
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Executing remote command
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: ${{ secrets.PORT }}
                  key: ${{ secrets.SSHKEY }}
                  envs: DISCORD_BOT_TOKEN,OPENAI_API_KEY
                  script: |
                      cd /home/blury/bot/discord/discord-bot-terracraft &&
                      docker build -f docker/Dockerfile -t discord-bot-terracraft .
                      docker-compose down &&
                      docker-compose up -d
